### ISSUE TITLE
Any example data?

### ISSUE THREAD

**Issue by brspurri** [eugene-bulkin/pycolley#1]
This looks like a great modification to the Colley Matrix approach.
I'd love to try your code out, but I was hoping to repeat it in it's exact for first (so I can step through it to understand it best as possible).

Do you have any sample implementation code?
Thanks!

**Comment by eugene-bulkin** [comment]
Sure! I'll make an examples folder and put some stuff in there.

**Comment by eugene-bulkin** [comment]
Added an example with NHL seasons in ded2c3e. The main point is that your data should be a tuple of 5 points, structured as `(team name 1, score 1, team name 2, score 2, notes)`.
